# Generated by Django 5.2.3 on 2025-06-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingsession',
            name='watermark_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
